[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
buildContext = "."

[deploy]
startCommand = "bash docker-entrypoint.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3
