ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS model_used TEXT;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS cost_usd DECIMAL(12,6) DEFAULT 0;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS latency_ms INTEGER DEFAULT 0;
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS fallback_used BOOLEAN DEFAULT FALSE;
